site_name: mkdocs-ml
site_url: https://amaralbf.github.io/mkdocs-ml/
repo_url: https://github.com/amaralbf/mkdocs-ml
repo_name: amaralbf/mkdocs-ml
site_author: Bruno Amaral

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    logo: material/file-document

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md

plugins:
  - search

extra_css:
  - css/style.css
